name: Django Test

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Coverage report For Changed Files
      run: |
        git show ${{github.event.after}}
        changed="$(git show ${{ github.event.after}})"
        echo $changed
          if [ -n "$changed" ];then
          files=""
          for modified_added in $changed; do
              files="$files $modified_added"
          done
        echo $files
        coverage report ${files}
        fi
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run manage.py test
    - name: Upload coverage reports to Codecov
      uses: Stingray-Upload.yml


