name: Django Test

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Run Tests
      run: |
        coverage run manage.py test
    - name: Upload coverage reports to Codecov
      uses: ./.github/workflows/Stingray-Upload.yml


