name: Django Test

on:
  pull_request:

  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v3
    - name: Upload coverage reports to Codecov
      uses: ./.github/workflows/action.yml


