name: Django Migration Test
on:
    push:
        branches:
            - 'alpha**'
        paths:
            '**migrations/**.py$'
jobs:
    runs-on: self-hosted
    steps:
        - uses: actions/checkout@v2
        - name: List changed migrations
        run: |
            git show --name-only ${{github.sha}}



